In [1]:
#1. Write a NumPy program to create an array with the values 1, 7, 13, 105    and determine the size of the memory occupied by the array.


In [12]:
import numpy as np

In [13]:
def function1():
    arr = np.array([1,7,13,105])
    print(arr)
    print(f"Type = {type(arr)}")
    print(f"Dtype = {arr.dtype}")
    print(f"Item Size = {arr.itemsize}")
    print(f"Size = {arr.size}")
    print(f"NDIM = {arr.ndim}")
    print(f"NBYTES = {arr.nbytes}")

In [14]:
function1()

[  1   7  13 105]
Type = <class 'numpy.ndarray'>
Dtype = int64
Item Size = 8
Size = 4
NDIM = 1
NBYTES = 32


In [15]:
#2. Write a NumPy program to create an element-wise comparison (greater,    greater_equal, less and less_equal) of two given arrays.


In [16]:
def function2():
    a_arr = np.array([10,20,30,40,50,60])
    b_arr = np.array([11,22,33,40,55,66])
    for i in range(0,5,1):
        if(a_arr[i]>b_arr[i]):
            print(f"{a_arr[i]} is greater than{b_arr[i]}")
        elif(a_arr[i]>=b_arr[i]):
            print(f"{a_arr[i]} is greater than{b_arr[i]} ")
        elif(a_arr[i]<b_arr[i]):
            print(f"{a_arr[i]} is less than{b_arr[i]}")

In [17]:
function2()

10 is less than11
20 is less than22
30 is less than33
40 is greater than40 
50 is less than55


In [18]:
# Write a NumPy program to create an array of 10 zeros, 10 ones, 10    fives, 10 tens, 10 twentys and 10 fiftys.

In [19]:
def function3():
    arr1 = np.zeros(10)
    print(arr1)
    arr2 = np.ones(10)
    print(arr2)
    print(arr2*5)
    print(arr2*20)
    print(arr2*15)

    

In [20]:
function3()

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[20. 20. 20. 20. 20. 20. 20. 20. 20. 20.]
[15. 15. 15. 15. 15. 15. 15. 15. 15. 15.]


In [21]:
#Write a NumPy program to create an array of integers from 30 to 70.


In [22]:
def function4():
    arr3 = np.arange(30,70)
    print(arr3)

In [23]:
function4()

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


In [24]:
#Write a NumPy program to create an array of integers from 50 to 95.


In [25]:
def function5():
    arr4 = np.arange(50,95)
    print(arr4)

In [26]:
function5()

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94]


In [27]:
#Write a NumPy program to create an array of all even integers from 20 to 80.

In [28]:
def function6():
    arr5 = np.arange(20,80,2)
    print(arr5)

In [29]:
function6()

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78]


In [30]:
#Write a NumPy program to create an array of all odd integers from 20 to 80.

In [31]:
def function7():
    arr6 = np.arange(21,80,2)
    print(arr6)

In [32]:
function7()

[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71 73 75 77 79]


In [33]:
#Write a NumPy program to generate an array of 15 random numbers from 10    to 40.

In [34]:
def function8():
    n1 = np.random.randint(10,40,15)
    print(n1)

In [35]:
function8()

[16 33 31 15 16 21 14 12 11 36 28 32 14 19 34]


In [36]:
# Write a NumPy program to generate an array of 10 random numbers from 30    to 50.


In [37]:
def function9():
    n2 = np.random.randint(30,50,10)
    print(n2)

In [38]:
function9()

[47 32 36 46 31 40 44 32 30 42]


In [39]:
#Write a NumPy program to generate an array of 20 random numbers from 50    to 90

In [40]:
def function10():
    n3 = np.random.randint(50,90,20)
    print(n3)

In [41]:
function10()

[74 56 83 75 86 59 50 50 78 59 83 77 84 76 62 85 83 83 71 65]


In [42]:
#Create any two arrays & perform various mathematical operations.
 #   i.e. Addition, Substraction, Multiplication, Divide.


In [43]:
def function11():
    n4 = np.array([20,30,40,60])
    n5 = np.array([2,3,4,6])
    print(f"N4 = {n4}")
    print(f"N5 = {n5}")
    print(f"adition = {n4+n5}")
    print(f"sub = {n4-n5}")
    print(f"mul = {n4*n5}")
    print(f"div = {n4/n5}")

In [44]:
function11()

N4 = [20 30 40 60]
N5 = [2 3 4 6]
adition = [22 33 44 66]
sub = [18 27 36 54]
mul = [ 40  90 160 360]
div = [10. 10. 10. 10.]


In [45]:
#Write a NumPy program to create a 3x4 matrix filled with values from 10     to 21.


In [46]:
def function12():
    n6 = np.arange(10,22).reshape(3, 4)
    print(n6)

In [47]:
function12()

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [48]:
#Q22. Write a NumPy program to convert an data type into to a floating type

In [49]:
def printProperties(arr):
    print(arr)
    print(f"Type = {type(arr)}")
    print(f"Dtype = {arr.dtype}")
    print(f"Item Size = {arr.itemsize}")
    print(f"Size = {arr.size}")
    print(f"NDIM = {arr.ndim}")
    print(f"NBYTES = {arr.nbytes}")

In [50]:
arr = np.array([1,7,13,105],dtype=np.float32)
printProperties(arr)


[  1.   7.  13. 105.]
Type = <class 'numpy.ndarray'>
Dtype = float32
Item Size = 4
Size = 4
NDIM = 1
NBYTES = 16


In [51]:
#Q19. Write a NumPy program to create a 3x3 matrix with values ranging from 2     to 10.

In [52]:
def function13():
    n7 = np.arange(2,11).reshape(3, 3)
    print(n7)

In [53]:
function13()

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [54]:
#13. Write a NumPy program to create a 3x3 identity matrix, i.e. the diagonal     elements are 1, the rest are 0.

In [55]:
def function14():
    n8 = np.diag([1,1,1])
    print(n8)

In [56]:
function14()

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [57]:
#14. Write a NumPy program to find the number of rows and columns in a given     matrix. 


In [58]:
def function15():
    n9 = np.arange(10,22).reshape(3, 4)
    print(f" number of rows and coloumn = {n9.shape}")

In [59]:
function15()

 number of rows and coloumn = (3, 4)


In [60]:
,#Q15 Write a NumPy program to create a 5x5 zero matrix with elements on the     main diagonal equal to 1, 2, 3, 4, 5.


In [61]:
def function16():
    n10 = np.diag([1,2,3,4,5])
    print(n10)

In [62]:
function16()

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [63]:
def function17():
    x = np.random.random([3,3,3])
    print(x)

In [64]:
function17()

[[[0.33664455 0.06962301 0.43322238]
  [0.09541368 0.71309233 0.4410983 ]
  [0.67164306 0.97921553 0.64562936]]

 [[0.09563613 0.71967083 0.49079956]
  [0.64868746 0.47631968 0.85157329]
  [0.39878215 0.81619078 0.52899585]]

 [[0.62300723 0.43018903 0.06235938]
  [0.32927568 0.82518366 0.84894632]
  [0.3185329  0.03002624 0.86989376]]]


In [65]:
#Q17. Write a NumPy program to create a 2x3x4 array filled with arbitrary     values.


In [66]:
def function18():
    x = np.random.random([2,3,4])
    print(x)

In [67]:
function18()

[[[0.04736967 0.06484381 0.88983484 0.51600609]
  [0.98363693 0.34706674 0.83735248 0.29618581]
  [0.49595796 0.78224153 0.34593184 0.32793204]]

 [[0.27836488 0.5192833  0.26466672 0.88828309]
  [0.39235621 0.38609648 0.14536132 0.81952039]
  [0.97585217 0.79179991 0.37048594 0.99214818]]]


In [68]:
#Q18. Write a NumPy program to convert a list of numeric values into a one-    dimensional NumPy array.

In [69]:
def function19():
 a = [1,2,3,4,5]
 b = np.array(a)
 print(b)

In [70]:
function19()

[1 2 3 4 5]


In [71]:
#Q20. Write a NumPy program to create an array with values ranging from 12 to 38.

In [72]:
def function20():
    n11= np.arange(12,38)
    print(n11)

In [73]:
function20()

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [74]:
#Q21. Write a NumPy program to reverse an array (the first element becomes the last).

In [75]:
def function21():
    x = np.arange(12, 38)
    print("Original array:")
    print(x)
    print("Reverse array:")
    x = x[::-1]
    print(x) 


In [76]:
function21()

Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [77]:
#23. Write a NumPy program to convert a list array.

In [78]:
def function22():
    l1 = [1, 2, 3, 4, 5, 6, 7,]
    print("List to array: ")
    print(np.asarray(l1))
    t1 = ([8, 4, 6], [1, 2, 3])
    print("Tuple to array: ")
    print(np.asarray(t1))

In [79]:
function22()

List to array: 
[1 2 3 4 5 6 7]
Tuple to array: 
[[8 4 6]
 [1 2 3]]


In [80]:
#Q24. Write a NumPy program to get the element-wise remainder of an array of division.


In [81]:
def function23():
    x = np.arange(7)
    print("Original array:")
    print(x)
    print("Element-wise remainder of division:")
    print(np.remainder(x, 5)) 

In [82]:
function23()

Original array:
[0 1 2 3 4 5 6]
Element-wise remainder of division:
[0 1 2 3 4 0 1]


In [83]:
#Q25. Write a NumPy program to get the element-wise remainder of an array of numbers from 20 to 50 which are divisible by 3.

In [84]:
def function23():
    x = np.arange(7)
    print("Original array:")
    print(x)
    print("Element-wise remainder of division:")
    print(np.remainder(x, 5)) 